# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be17fd72b7eb702ff7663d2ea3a089be163730486b1eb848de6aae8280532ea7f6e8b69528f9b822e7c610986841c071c88375d2f0717d677a58648356b92a5e

test:
  secret_key_base: a216168832ad3d95712496dd2ae69f4065e66815e59114ee34eaca75f1339ad6d8d616cf92598f55798f53c64209fbd786b16fcd27ee51ce0fc894c6df9ee59d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
